### ISSUE TITLE
Connect to Endpoint

### ISSUE THREAD

**Issue by NCasuttSFA** [bergos/sparql-http-client#30]
Hi, Im trying to connect to an Endpoint and retrieve a stream with SparqlClient from sparql-http-client. If I connect to http://dbpedia.org/sparql as example everything seems to work. By changing the URL to another Endpoint, I get the error message "Unexpected "!" at position 2 in state STOP". I see that there are different options when creating the SparqlClient and I found some examples, but I cant find any documentation on it. Do you have any reference? Thank you a lot!

**Comment by l00mi** [comment]
Can you provide your example which does not work?

**Comment by tpluscode** [comment]
Regarding docs, have you checked https://zazuko.github.io/sparql-http-client/? There is also a DT package `@types/sparql-http-client`

**Comment by dabuchera** [comment]
Maybe helpful

https://github.com/zazuko/sparql-http-client/issues/40

**Comment by bergos** [comment]
Closed because of inactivity.
