### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by yannismate** [bergos/sparql-http-client#31]
I would like to use this code in an open source project. Any way a license could be added to this repository to clarify which use-cases are allowed?
Thanks!

**Comment by ktk** [comment]
Thanks for the catch, we will add it. It's MIT as mentioned in the [package.json](https://github.com/zazuko/sparql-http-client/blob/fab1acd891a8f935fe1c9e64de7374e4022caaf0/package.json#L20)

**Comment by bergos** [comment]
fixed in #56
