### ISSUE TITLE
Sample at NPM homepage contains error

### ISSUE THREAD

**Issue by semanticfire** [bergos/sparql-http-client#33]
The sample at the NPM homepage has an error:
`const client = new SparqlClient({ endpointUrl })`

should read:
`const client = new SparqlClient({ endpointUrl: endpointUrl })`

**Comment by bergos** [comment]
That's valid JS code. See [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) mdn page. It was introduced with ES6.
