### ISSUE TITLE
how to add Basic Auth like username password?

### ISSUE THREAD

**Issue by jayeshdesai4520** [bergos/sparql-http-client#34]
Hi, I am trying to add username and password but I am having problem like where to add it?

**Comment by tpluscode** [comment]
See on the docs index: https://zazuko.github.io/sparql-http-client/#/?id=creating-a-client

You typically pass in `user/password` to the configuration of your client object.

Alternatively you can embed the credentials directly in the endpoint URL such as `http://user:password@localhost:3030/sparql`
