### ISSUE TITLE
No docs?

### ISSUE THREAD

**Issue by bolerio** [bergos/sparql-http-client#41]
Can't find any documentation, besides the example on the main page of course, on how to use this library. The link `https://zazuko.github.io/sparql-http-client` is broken. Seems ike Zazuko is a private company and this repo is no long public perhaps? Is the library being taken closed source for further development? Suggestions for alternatives? Thanks!

**Comment by bergos** [comment]
Sorry for the broken link. I fixed it. [Here](https://bergos.github.io/sparql-http-client/) you can find the documentation. The library is still maintained and is now located under my user, as I am the main maintainer.

**Comment by bolerio** [comment]
Many thanks @bergos ! Link works.
